// Code generated by protoc-gen-gogo.
// source: commonpb/raft.proto
// DO NOT EDIT!

/*
	Package commonpb is a generated protocol buffer package.

	It is generated from these files:
		commonpb/raft.proto

	It has these top-level messages:
		Entry
		Snapshot
		ConfChangeRequest
		ConfChangeResponse
*/
package commonpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EntryType int32

const (
	EntryInternal   EntryType = 0
	EntryNormal     EntryType = 1
	EntryConfChange EntryType = 2
)

var EntryType_name = map[int32]string{
	0: "EntryInternal",
	1: "EntryNormal",
	2: "EntryConfChange",
}
var EntryType_value = map[string]int32{
	"EntryInternal":   0,
	"EntryNormal":     1,
	"EntryConfChange": 2,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}
func (EntryType) EnumDescriptor() ([]byte, []int) { return fileDescriptorRaft, []int{0} }

type ConfType int32

const (
	ConfAdd    ConfType = 0
	ConfRemove ConfType = 1
)

var ConfType_name = map[int32]string{
	0: "ConfAdd",
	1: "ConfRemove",
}
var ConfType_value = map[string]int32{
	"ConfAdd":    0,
	"ConfRemove": 1,
}

func (x ConfType) String() string {
	return proto.EnumName(ConfType_name, int32(x))
}
func (ConfType) EnumDescriptor() ([]byte, []int) { return fileDescriptorRaft, []int{1} }

type ConfStatus int32

const (
	ConfOK      ConfStatus = 0
	ConfTimeout ConfStatus = 2
)

var ConfStatus_name = map[int32]string{
	0: "ConfOK",
	2: "ConfTimeout",
}
var ConfStatus_value = map[string]int32{
	"ConfOK":      0,
	"ConfTimeout": 2,
}

func (x ConfStatus) String() string {
	return proto.EnumName(ConfStatus_name, int32(x))
}
func (ConfStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorRaft, []int{2} }

type Entry struct {
	Term      uint64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index     uint64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	EntryType EntryType `protobuf:"varint,3,opt,name=entryType,proto3,enum=commonpb.EntryType" json:"entryType,omitempty"`
	Data      []byte    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptorRaft, []int{0} }

type Snapshot struct {
	LeaderID          uint64 `protobuf:"varint,1,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Term              uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastIncludedIndex uint64 `protobuf:"varint,3,opt,name=lastIncludedIndex,proto3" json:"lastIncludedIndex,omitempty"`
	LastIncludedTerm  uint64 `protobuf:"varint,4,opt,name=lastIncludedTerm,proto3" json:"lastIncludedTerm,omitempty"`
	Data              []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptorRaft, []int{1} }

type ConfChangeRequest struct {
	Addr     string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	ConfType ConfType `protobuf:"varint,2,opt,name=confType,proto3,enum=commonpb.ConfType" json:"confType,omitempty"`
}

func (m *ConfChangeRequest) Reset()                    { *m = ConfChangeRequest{} }
func (m *ConfChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfChangeRequest) ProtoMessage()               {}
func (*ConfChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptorRaft, []int{2} }

type ConfChangeResponse struct {
	Status     ConfStatus `protobuf:"varint,1,opt,name=status,proto3,enum=commonpb.ConfStatus" json:"status,omitempty"`
	LeaderHint string     `protobuf:"bytes,2,opt,name=leaderHint,proto3" json:"leaderHint,omitempty"`
}

func (m *ConfChangeResponse) Reset()                    { *m = ConfChangeResponse{} }
func (m *ConfChangeResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfChangeResponse) ProtoMessage()               {}
func (*ConfChangeResponse) Descriptor() ([]byte, []int) { return fileDescriptorRaft, []int{3} }

func init() {
	proto.RegisterType((*Entry)(nil), "commonpb.Entry")
	proto.RegisterType((*Snapshot)(nil), "commonpb.Snapshot")
	proto.RegisterType((*ConfChangeRequest)(nil), "commonpb.ConfChangeRequest")
	proto.RegisterType((*ConfChangeResponse)(nil), "commonpb.ConfChangeResponse")
	proto.RegisterEnum("commonpb.EntryType", EntryType_name, EntryType_value)
	proto.RegisterEnum("commonpb.ConfType", ConfType_name, ConfType_value)
	proto.RegisterEnum("commonpb.ConfStatus", ConfStatus_name, ConfStatus_value)
}
func (m *Entry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Entry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Term != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.Term))
	}
	if m.Index != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.Index))
	}
	if m.EntryType != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.EntryType))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintRaft(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.LeaderID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.LeaderID))
	}
	if m.Term != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.Term))
	}
	if m.LastIncludedIndex != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.LastIncludedIndex))
	}
	if m.LastIncludedTerm != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.LastIncludedTerm))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintRaft(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *ConfChangeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfChangeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRaft(dAtA, i, uint64(len(m.Addr)))
		i += copy(dAtA[i:], m.Addr)
	}
	if m.ConfType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.ConfType))
	}
	return i, nil
}

func (m *ConfChangeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfChangeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRaft(dAtA, i, uint64(m.Status))
	}
	if len(m.LeaderHint) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRaft(dAtA, i, uint64(len(m.LeaderHint)))
		i += copy(dAtA[i:], m.LeaderHint)
	}
	return i, nil
}

func encodeFixed64Raft(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Raft(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintRaft(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Entry) Size() (n int) {
	var l int
	_ = l
	if m.Term != 0 {
		n += 1 + sovRaft(uint64(m.Term))
	}
	if m.Index != 0 {
		n += 1 + sovRaft(uint64(m.Index))
	}
	if m.EntryType != 0 {
		n += 1 + sovRaft(uint64(m.EntryType))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRaft(uint64(l))
	}
	return n
}

func (m *Snapshot) Size() (n int) {
	var l int
	_ = l
	if m.LeaderID != 0 {
		n += 1 + sovRaft(uint64(m.LeaderID))
	}
	if m.Term != 0 {
		n += 1 + sovRaft(uint64(m.Term))
	}
	if m.LastIncludedIndex != 0 {
		n += 1 + sovRaft(uint64(m.LastIncludedIndex))
	}
	if m.LastIncludedTerm != 0 {
		n += 1 + sovRaft(uint64(m.LastIncludedTerm))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRaft(uint64(l))
	}
	return n
}

func (m *ConfChangeRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovRaft(uint64(l))
	}
	if m.ConfType != 0 {
		n += 1 + sovRaft(uint64(m.ConfType))
	}
	return n
}

func (m *ConfChangeResponse) Size() (n int) {
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovRaft(uint64(m.Status))
	}
	l = len(m.LeaderHint)
	if l > 0 {
		n += 1 + l + sovRaft(uint64(l))
	}
	return n
}

func sovRaft(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRaft(x uint64) (n int) {
	return sovRaft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Entry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Entry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Entry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryType", wireType)
			}
			m.EntryType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntryType |= (EntryType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRaft
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRaft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Snapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Snapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Snapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderID", wireType)
			}
			m.LeaderID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeaderID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastIncludedIndex", wireType)
			}
			m.LastIncludedIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastIncludedIndex |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastIncludedTerm", wireType)
			}
			m.LastIncludedTerm = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastIncludedTerm |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRaft
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRaft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfChangeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfChangeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfChangeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRaft
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfType", wireType)
			}
			m.ConfType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConfType |= (ConfType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRaft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRaft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfChangeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfChangeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfChangeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (ConfStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderHint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRaft
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaderHint = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRaft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRaft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRaft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRaft
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRaft
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRaft(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRaft = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaft   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("commonpb/raft.proto", fileDescriptorRaft) }

var fileDescriptorRaft = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x52, 0x5b, 0x6e, 0xd3, 0x40,
	0x14, 0xf5, 0xb8, 0x49, 0x70, 0x6e, 0x21, 0x75, 0x6e, 0xfa, 0x61, 0xf5, 0xc3, 0x8a, 0xf2, 0x43,
	0x88, 0x8a, 0x23, 0xca, 0x0a, 0x20, 0xad, 0x44, 0x84, 0x04, 0x92, 0x5b, 0x89, 0xef, 0x71, 0x66,
	0xf2, 0x90, 0xec, 0x19, 0x63, 0x8f, 0x51, 0xbb, 0x0b, 0x96, 0xc1, 0x52, 0xfa, 0xd9, 0x25, 0xd0,
	0xb0, 0x11, 0xe4, 0xeb, 0xc4, 0x71, 0x95, 0xbf, 0x73, 0xce, 0x3d, 0x73, 0xee, 0xd1, 0xb5, 0x61,
	0xb0, 0xd0, 0x49, 0xa2, 0x55, 0x1a, 0x4d, 0x33, 0xbe, 0x34, 0x41, 0x9a, 0x69, 0xa3, 0xd1, 0xd9,
	0x8b, 0x17, 0xef, 0x57, 0x1b, 0xb3, 0x2e, 0xa2, 0x60, 0xa1, 0x93, 0xe9, 0x4a, 0xaf, 0xf4, 0x94,
	0x0c, 0x51, 0xb1, 0x24, 0x46, 0x84, 0x50, 0xf5, 0x70, 0x74, 0x0f, 0xed, 0x1b, 0x65, 0xb2, 0x07,
	0x44, 0x68, 0x19, 0x99, 0x25, 0x1e, 0x1b, 0xb2, 0x71, 0x2b, 0x24, 0x8c, 0xe7, 0xd0, 0xde, 0x28,
	0x21, 0xef, 0x3d, 0x9b, 0xc4, 0x8a, 0xe0, 0x07, 0xe8, 0xca, 0xf2, 0xc9, 0xdd, 0x43, 0x2a, 0xbd,
	0x93, 0x21, 0x1b, 0xf7, 0xae, 0x06, 0xc1, 0x7e, 0x7f, 0x70, 0xb3, 0x1f, 0x85, 0x07, 0x57, 0x19,
	0x2e, 0xb8, 0xe1, 0x5e, 0x6b, 0xc8, 0xc6, 0xaf, 0x43, 0xc2, 0xa3, 0x3f, 0x0c, 0x9c, 0x5b, 0xc5,
	0xd3, 0x7c, 0xad, 0x0d, 0x5e, 0x80, 0x13, 0x4b, 0x2e, 0x64, 0x36, 0xbf, 0xde, 0x35, 0xa8, 0x79,
	0xdd, 0xcc, 0x6e, 0x34, 0xbb, 0x84, 0x7e, 0xcc, 0x73, 0x33, 0x57, 0x8b, 0xb8, 0x10, 0x52, 0xcc,
	0xa9, 0xe5, 0x09, 0x19, 0x8e, 0x07, 0x38, 0x01, 0xb7, 0x29, 0xde, 0x95, 0x69, 0x2d, 0x32, 0x1f,
	0xe9, 0x75, 0xd5, 0x76, 0xa3, 0xea, 0x0f, 0xe8, 0xcf, 0xb4, 0x5a, 0xce, 0xd6, 0x5c, 0xad, 0x64,
	0x28, 0x7f, 0x16, 0x32, 0x37, 0xa5, 0x91, 0x0b, 0x91, 0x51, 0xdd, 0x6e, 0x48, 0x18, 0x03, 0x70,
	0x16, 0x5a, 0x2d, 0xe9, 0x32, 0x36, 0x5d, 0x06, 0x0f, 0x97, 0x99, 0xed, 0x26, 0x61, 0xed, 0x19,
	0x45, 0x80, 0xcd, 0xe0, 0x3c, 0xd5, 0x2a, 0x97, 0x78, 0x09, 0x9d, 0xdc, 0x70, 0x53, 0xe4, 0x94,
	0xdd, 0xbb, 0x3a, 0x7f, 0x99, 0x71, 0x4b, 0xb3, 0x70, 0xe7, 0x41, 0x1f, 0xa0, 0x3a, 0xd5, 0x97,
	0x8d, 0x32, 0xb4, 0xb5, 0x1b, 0x36, 0x94, 0xc9, 0x35, 0x74, 0xeb, 0x6f, 0x82, 0x7d, 0x78, 0x43,
	0x64, 0xae, 0x8c, 0xcc, 0x14, 0x8f, 0x5d, 0x0b, 0xcf, 0xe0, 0x94, 0xa4, 0x6f, 0x3a, 0x4b, 0x78,
	0xec, 0x32, 0x1c, 0xc0, 0x19, 0x09, 0x87, 0x66, 0xae, 0x3d, 0x79, 0x0b, 0xce, 0xbe, 0x3f, 0x9e,
	0xc2, 0xab, 0x12, 0x7f, 0x12, 0xc2, 0xb5, 0xb0, 0x07, 0x50, 0x92, 0x50, 0x26, 0xfa, 0x97, 0x74,
	0xd9, 0xe4, 0x5d, 0xc5, 0xab, 0x92, 0x08, 0xd0, 0x29, 0xd9, 0xf7, 0xaf, 0xd5, 0x22, 0x8a, 0xd8,
	0x24, 0x52, 0x17, 0xc6, 0xb5, 0x3f, 0x7b, 0x8f, 0xcf, 0xbe, 0xf5, 0xf4, 0xec, 0x5b, 0x8f, 0x5b,
	0x9f, 0x3d, 0x6d, 0x7d, 0xf6, 0x77, 0xeb, 0xb3, 0xdf, 0xff, 0x7c, 0x2b, 0xea, 0xd0, 0xcf, 0xf9,
	0xf1, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x28, 0xd9, 0xfd, 0xec, 0x02, 0x00, 0x00,
}
