* Raft Consensus with Gorums

** Replica

  =replica= starts a raft server listening on the ip:port provided through the =-listen= argument.
  You need to start more than one raft server to form a operational raft cluster.
  The other servers in the cluster is given through multiple =-add= arguments, one for each server.
  If you want a server to recover from stable storage pass the =-recover= argument.
  The =-quiet= argument will silence all log output.
  Setting =-batch= to false will limit the number entries per message to 1, and new entries will be tried committed immediately.
  =-qrpc= enables the use of a quorum function for AppendEntries.
  When =-qrpc= is enabled only the fastest followers will stay up-to-date, to force all servers to replicate an entry before committing, one can set =-slowquorum=.
  Without =-qrpc= enabled =replica= is limited to exactly 3 servers.

*** Usage
#+BEGIN_EXAMPLE
Usage of replica:
  -add value
    	Remote server address, repeat argument for each server in the cluster
  -batch
    	enable batching (default true)
  -cpuprofile string
    	Write cpu profile to file
  -listen string
    	Local server address
  -qrpc
    	enable QRPC
  -quiet
    	Silence log output
  -recover
    	Recover from stable storage
  -slowquorum
    	set quorum size to the number of servers
#+END_EXAMPLE

*** Example
**** Separate machines
#+BEGIN_SRC shell
# Computer with IP1.
replica -listen IP1:9200 -add IP2:9200 -add IP3:9200

# Computer with IP2.
replica -listen IP2:9200 -add IP1:9200 -add IP3:9200

# Computer with IP3.
replica -listen IP3:9200 -add IP2:9200 -add IP1:9200

# Computer(s) with client(s).
## Do something, i.e, run latency/throughput.
#+END_SRC

**** Same machine (same shell)
You can omit the ip to listen on localhost.

#+BEGIN_SRC shell
replica -listen :9201 -add :9202 -add :9203 &
replica -listen :9202 -add :9201 -add :9203 &
replica -listen :9203 -add :9202 -add :9201 &

## Do something (preferably in another shell, unless you add -quiet), i.e, run latency/throughput.
## Stop cluster when you are done.
killall replica
#+END_SRC

*** For client interaction:
- [[https://github.com/relab/raft/tree/master/cmd/throughput][Throughput]]
- [[https://github.com/relab/raft/tree/master/cmd/latency][Latency]]
