#! /bin/bash

set -e

go build

./replica -this :9202 -node :9201 -node :9203 -verbosity 1 -recover &
./replica -this :9203 -node :9201 -node :9202 -verbosity 1 -recover &
./replica -this :9201 -node :9202 -node :9203 -verbosity 1 -recover &

read && killall replica
